//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "activity_samples")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub window_start: DateTime,
    pub window_end: DateTime,
    #[sea_orm(column_type = "Text")]
    pub classification: String,
    pub accel_magnitude_mean: Option<f64>,
    pub accel_magnitude_std: Option<f64>,
    pub gyro_magnitude_mean: Option<f64>,
    pub dominant_frequency_hz: Option<f64>,
    pub mean_hr: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
