//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "dev_notes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: DateTime,
    #[sea_orm(column_type = "Text")]
    pub author: String,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub body_md: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub related_commit: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub related_feature: Option<String>,
    pub related_range_start: Option<DateTime>,
    pub related_range_end: Option<DateTime>,
    pub resolved_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resolved_by: Option<String>,
    pub payload_json: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
