//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "device_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub recorded_at: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    pub harvard_version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub boylston_version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub device_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
