//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "hrv_samples")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub window_start: DateTime,
    pub window_end: DateTime,
    pub rmssd: f64,
    pub sdnn: Option<f64>,
    pub mean_hr: f64,
    pub rr_count: i32,
    pub stillness_ratio: f64,
    #[sea_orm(column_type = "Text")]
    pub context: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
