//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "sleep_epochs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sleep_cycle_id: Uuid,
    pub epoch_start: DateTime,
    pub epoch_end: DateTime,
    #[sea_orm(column_type = "Text")]
    pub stage: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub confidence: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub hr_mean: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub hr_std: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub hr_min: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub hr_max: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub rmssd: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub sdnn: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub pnn50: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub lf_power: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub hf_power: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub lf_hf_ratio: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub motion_activity_count: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub motion_stillness_ratio: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub resp_rate: Option<f64>,
    pub feature_blob: Option<Json>,
    #[sea_orm(column_type = "Text")]
    pub classifier_version: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sleep_cycles::Entity",
        from = "Column::SleepCycleId",
        to = "super::sleep_cycles::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SleepCycles,
}

impl Related<super::sleep_cycles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SleepCycles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
