//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "sync_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub attempt_started_at: DateTime,
    pub attempt_ended_at: Option<DateTime>,
    #[sea_orm(column_type = "Text")]
    pub outcome: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub heart_rate_rows_added: Option<i32>,
    pub packets_downloaded: Option<i32>,
    pub sleep_cycles_created: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub trigger: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
