//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "user_baselines")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub computed_at: DateTime,
    pub window_nights: i32,
    #[sea_orm(column_type = "Double", nullable)]
    pub resting_hr: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub sleep_rmssd_median: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub sleep_rmssd_p25: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub sleep_rmssd_p75: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub hf_power_median: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub lf_hf_ratio_median: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub sleep_duration_mean_hours: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub respiratory_rate_mean: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub respiratory_rate_std: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub skin_temp_mean_c: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub skin_temp_std_c: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
