//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wear_periods")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub start: DateTime,
    pub end: DateTime,
    #[sea_orm(column_type = "Text")]
    pub source: String,
    pub duration_minutes: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
